services:
  bidfe-app:
    build:
      context: .
      dockerfile: Dockerfile
      # Ensure your Dockerfile CMD runs `npm run dev` for local dev
    container_name: bidfe_frontend
    restart: always
    ports:
      - "5173:5173" # Changed from 80 to 5173 for the Vite dev server
    volumes:
      - .:/app # Mount source code for hot-reloading
      - /app/node_modules # Prevent host node_modules from overwriting container's
    networks:
      - app-network

networks:
  app-network:
    driver: bridge