server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip for performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location / {
        # Handle React Routing (Redirect 404s to index.html)
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets (JS/CSS)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}