import type { CSSProperties } from "react";

const styles = {

    link: { textDecoration: "none", color: "inherit", display: "block" } as CSSProperties,
    container: {
        background: "var(--bg-card)",
        boxShadow: "0 4px 12px rgba(0,0,0,0.05)",
        border: "none",
        backdropFilter: "blur(12px)",
        WebkitBackdropFilter: "blur(12px)",
        borderRadius: "4px",
        overflow: "hidden",
        cursor: "pointer",
        transition: "transform 0.2s, box-shadow 0.2s, background-color 0.3s ease, border-color 0.3s ease",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        flexGrow: 1,
        minWidth: 0,
    } as CSSProperties,

    imageWrapper: {
        aspectRatio: "4/3",
        flexShrink: 0,
        width: "100%",
        background: "var(--bg-input)",
        position: "relative",
        overflow: "hidden",
        transition: "background-color 0.3s ease",
    } as CSSProperties,
    image: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        display: "block",
    } as CSSProperties,
    placeholder: {
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "var(--text-muted)",
        fontSize: "12px",
        textTransform: "uppercase",
        transition: "color 0.3s ease",
    } as CSSProperties,

    content: { padding: "12px", flexGrow: 1, display: "flex", flexDirection: "column" } as CSSProperties,
    title: {
        margin: "0 0 4px 0",
        fontSize: "18px",
        fontWeight: 800,
        color: "var(--text-primary)",
        lineHeight: 1.25,
        transition: "color 0.3s ease",
    } as CSSProperties,
    year: {
        fontWeight: 800,
        color: "var(--text-secondary)",
        transition: "color 0.3s ease",
    } as CSSProperties,

    // Metadata & Footer
    metaRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        marginBottom: "4px",
    } as CSSProperties,
    labelText: {
        fontSize: "10px",
        color: "var(--text-muted)",
        fontWeight: 700,
        letterSpacing: "0.5px",
        marginBottom: "2px",
        textTransform: "uppercase",
        transition: "color 0.3s ease",
    } as CSSProperties,
    priceText: {
        fontSize: "18px",
        fontWeight: 700,
        color: "var(--text-primary)",
        fontVariantNumeric: "tabular-nums",
        transition: "color 0.3s ease",
    } as CSSProperties,
    locationText: {
        fontSize: "13px",
        color: "var(--text-secondary)",
        fontWeight: 500,
        transition: "color 0.3s ease",
    } as CSSProperties,
    specsText: {
        fontSize: "12px",
        color: "var(--text-muted)",
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
        marginTop: "8px",
        borderTop: "1px solid var(--border-color)",
        paddingTop: "8px",
        transition: "color 0.3s ease, border-color 0.3s ease",
    } as CSSProperties,

    overlayTopLeft: { position: "absolute", top: "10px", left: "10px", zIndex: 2 } as CSSProperties,
    overlayTopRight: { position: "absolute", top: "10px", right: "10px", zIndex: 2 } as CSSProperties,
    overlayBottomContainer: {
        position: "absolute",
        bottom: "10px",
        left: "10px",
        right: "10px",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        zIndex: 2
    } as CSSProperties,

    badge: {
        padding: "4px 8px",
        borderRadius: "4px",
        fontSize: "11px",
        fontWeight: 700,
        letterSpacing: "0.5px",
        textTransform: "uppercase",
        boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
        background: "var(--bg-base)",
        color: "var(--text-primary)",
        transition: "background-color 0.3s ease, color 0.3s ease",
    } as CSSProperties,

    badgeEnded: {
        background: "var(--text-muted)",
        color: "var(--bg-base)",
        padding: "4px 8px",
        borderRadius: "4px",
        fontSize: "11px",
        fontWeight: 700,
        letterSpacing: "0.5px",
        transition: "background-color 0.3s ease, color 0.3s ease",
    } as CSSProperties,

    badgeDark: {
        background: "rgba(0, 0, 0, 0.7)",
        color: "white",
        padding: "4px 8px",
        borderRadius: "4px",
        fontSize: "11px",
        fontWeight: 600,
        backdropFilter: "blur(4px)",
    } as CSSProperties,

    badgeLive: {
        background: "rgba(0, 0, 0, 0.8)",
        color: "#fff",
        padding: "4px 8px",
        borderRadius: "4px",
        fontSize: "10px",
        fontWeight: 700,
        display: "flex",
        alignItems: "center",
        gap: "6px",
        letterSpacing: "0.5px",
    } as CSSProperties,

    badgeTimer: {
        padding: "4px 8px",
        borderRadius: "20px",
        fontSize: "12px",
        fontWeight: 700,
        display: "flex",
        alignItems: "center",
        fontVariantNumeric: "tabular-nums",
        boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
        background: "var(--bg-base)",
        color: "var(--text-primary)",
        transition: "background-color 0.3s ease, color 0.3s ease",
    } as CSSProperties,

    dot: {
        width: "6px",
        height: "6px",
        borderRadius: "50%",
        backgroundColor: "var(--color-danger-text)",
        display: "block",
        transition: "background-color 0.3s ease",
    } as CSSProperties,
};

export default styles;