steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/bidapi-repo/bidapi', '.']

# 2. Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/bidapi-repo/bidapi']

# 3. Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'bidapi'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/bidapi-repo/bidapi'
  - '--region'
  - 'us-central1' # Replace with your preferred region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--add-cloudsql-instances'
  - 'bidyourcarapp:us-central1:car-auction-db'
  - '--min-instances'
  - '1'
  - '--cpu-boost'
  - '--update-env-vars'
  - '^|^SPRING_DATASOURCE_URL=jdbc:postgresql:///carauction?cloudSqlInstance=bidyourcarapp:us-central1:car-auction-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory|SPRING_DATASOURCE_USERNAME=postgres|SPRING_DATASOURCE_PASSWORD=bidyourcar_secure_db_pass_2026!|JWT_SECRET_KEY=5b8b6ae7ddd01461f93a72cebaf4e60b917f416ff76c59700eaf6257d578a55a|R2_BUCKET_NAME=bidapi-objectstorage|R2_ACCESS_KEY=384140c1d7ea8ddd4b6a15b10535d70e|R2_SECRET_KEY=3942b50922f29fcc74f3855e1fb23bd61f3020174e15a70f238aa40e9378eb1f|R2_ACCOUNT_ID=3a7f8715796ad70c68764a8e48def3ef|R2_PUBLIC_URL=https://pub-xxxxxx.r2.dev/|MAIL_USERNAME=7046cc40e80611|MAIL_PASSWORD=da2f30a4472dec|APP_COOKIE_SECURE=true|APP_COOKIE_SAME_SITE=None|APP_FRONTEND_URL=http://localhost:5173|APP_FEATURES_EMAIL_VERIFICATION_ENABLED=false|CORS_ALLOWED_ORIGINS=http://localhost:5173'

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/bidapi-repo/bidapi
