services:
  db:
    image: postgres:15
    container_name: car-auction-db
    restart: always
    environment:
      POSTGRES_DB: carauction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - car-auction-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: car-auction-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carauction
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
    ports:
      - "8080:8080"
    restart: always

volumes:
  car-auction-data: