name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          cd bidfe
          npm install
          npm run build

      - name: Deploy Preview to Firebase
        run: |
          cd bidfe
          npx firebase-tools hosting:channel:deploy pr-${{ github.event.number }} --expires 7d --project project-d2f657cf-d1e8-4e22-97a --token ${{ secrets.FIREBASE_TOKEN }}
