spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        time_zone: UTC

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: f251d039e25de7
    password: c01f28a5e4b9d7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret:
    key: "thisissecretkeyformypersonalspringbootapp"
  expiration: 86400000

cors:
  allowed-origins: "http://localhost:5173,http://localhost:8080,http://localhost:3000"

aws:
  s3:
    bucket: ${AWS_BUCKET}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: "eu-north-1"
  cdn:
    base-url: "https://ik.imagekit.io/lfv0hg4nv"