spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      jdbc:
        time_zone: UTC

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration: 86400000

cors:
  allowed-origins:
  - "http://localhost:5173"
  - "http://localhost:8080"
  - "https://bidyourcar.web.app"

cloudflare:
  r2:
    bucket: ${R2_BUCKET_NAME}
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    endpoint: "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    region: "auto"

imagekit:
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: TRACE
